# Sources for this workflow:
#
# * https://github.com/actions/cache/blob/master/examples.md#node---npm
# * https://github.com/cypress-io/cypress-example-kitchensink/blob/master/.github/workflows/single.yml
#
name: Build
on: [push]
jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: "Set up Node"
        uses: actions/setup-node@v1
        with:
          node-version: 10.16.3
      - name: "Set up Elm environment"
        run: |
          curl -L -o elm.gz https://github.com/elm/compiler/releases/download/0.19.0/binary-for-mac-64-bit.gz &&
            gunzip elm.gz &&
            chmod +x elm &&
            sudo mv elm /usr/local/bin/
      - name: "Check out code"
        uses: actions/checkout@v1
      - name: "Cache Node modules"
        uses: actions/cache@v1
        with:
          path: ~/.npm
          key: build-npm-${{ hashFiles('**/package-lock.json') }}
      #- name: Cache Cypress binary
        #uses: actions/cache@v1
        #with:
          #path: ~/.cache/Cypress
          #key: build-cypress-${{ hashFiles('**/package.json') }}
      - name: "Install JavaScript dependencies"
        env:
          # make sure every Cypress install prints minimal information
          CI: 1
        run: "npm ci"
      - name: "Verify Cypress"
        run: "npx cypress verify"
      - name: "Clear elm-stuff"
        run: "rm -rf elm-stuff && mkdir elm-stuff"
      - name: "Build app"
        run: "npm run build"
      - name: "Run Cypress tests"
        run: "npm run ci"
      # Save videos and screenshots as test artifacts
      # https://github.com/actions/upload-artifact
      - uses: actions/upload-artifact@master
        with:
          name: screenshots
          path: cypress/screenshots
          # there might be no screenshots created when:
          # - there are no test failures
          # so only upload screenshots if previous step has failed
          if: failure()
      # videos should always be generated
      - uses: actions/upload-artifact@master
        with:
          name: videos
          path: cypress/videos
